name: build and deploy production

env:
  REGISTRY_URL: ghcr.io
  FULL_IMAGE_NAME: ghcr.io/${{ github.actor }}/rfqm-prod
  NEW_TAG: ${{ github.sha }}

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: authenticate to ghcr
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          tags: |
            ${{ env.FULL_IMAGE_NAME }}:latest
            ${{ env.FULL_IMAGE_NAME }}:${{ env.NEW_TAG }}

      - name: deploy via ssh
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/devops/rfqm-prod

            docker login ghcr.io -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}

            docker compose pull rfqm-prod
            docker compose up -d

            echo "done!"
