name: build and deploy staging

on:
  push:
    branches: ["staging"]

env:
  REGISTRY_URL: registry.rfqm.xyz
  FULL_IMAGE_NAME: registry.rfqm.xyz/rfqm
  IMAGE_TAG: staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: authenticate to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY_URL }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: build and push docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          tags: |
            ${{ env.FULL_IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ${{ env.FULL_IMAGE_NAME }}:${{ github.sha }}

      - name: deploy via ssh
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/devops/rfqm-staging

            echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login ${{ env.REGISTRY_URL }} -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

            docker compose pull rfqm-staging
            docker compose up -d

            echo "done!"
